---
- name: set only specific galaxy-repos
  lineinfile:
    path: "/etc/cvmfs/default.local"
    regexp: '(^CVMFS_REPOSITORIES=)'
    line: 'CVMFS_REPOSITORIES="{{",".join(repos) }}"'
    state: present
  tags: repo

- name: install and configure elixir-it client
  block:
    - name: download elixir-italy-cvmfs configs
      get_url:
        url: 'https://raw.githubusercontent.com/indigo-dc/Reference-data-galaxycloud-repository/master/{{ item.conf_file }}/{{ la_cvmfs_repository }}.{{ item.ext }}'
        dest: '/etc/cvmfs/{{ item.dest_dir }}/{{ la_cvmfs_repository }}.{{ item.ext }}'
      with_items:
        - { conf_file: cvmfs_server_config_files, dest_dir: config.d, ext: conf }
        - { conf_file: cvmfs_server_keys, dest_dir: keys, ext: pub }
    
    - name: check if the config is already set
      lineinfile: 
        dest: /etc/cvmfs/default.local
        regexp: "{{ la_cvmfs_repository }}"
        state: present
        line: "check presence"
      check_mode: yes
      register: repo_exist
    
    - name: append elixir-cvmfs-repo to config
      lineinfile:
        path: "/etc/cvmfs/default.local"
        backrefs: yes
        regexp: '(^CVMFS_REPOSITORIES=.+?(?="))'
        line: '\1,{{ la_cvmfs_repository }}"'
        state: present
      when: repo_exist
    
    - name: set GARR stratum 1
      block:
        - name: set galaxy repo stratum 1
          lineinfile:
            path: "/etc/cvmfs/domain.d/galaxyproject.org.conf"
            backrefs: yes
            regexp: '(^CVMFS_SERVER_URL=)'
            line: '\1"http://cvmfs1-garr0.cloud.garrservices.it/cvmfs/@fqrn@"'
            state: present
          
        - name: set galaxy repo stratum 1
          lineinfile:
            path: "/etc/cvmfs/config.d/data.elixir-italy-cvmfs.conf"
            backrefs: yes
            regexp: '(^CVMFS_SERVER_URL=)'
            line: '\1http://elixirit1-garr0.cloud.garrservices.it/cvmfs/data.elixir-italy-cvmfs'
            state: present
      when: garr_mirrors

  when: elixir_it_repo
  tags: elixir-repo

 
