---
# tasks file for cvmfs-client-elixir-it
- name: run galaxyproject cvmfs role
  include_role:
    name: galaxyproject.cvmfs

- name: download elixir-italy-cvmfs config
  get_url:
    url: 'https://raw.githubusercontent.com/indigo-dc/Reference-data-galaxycloud-repository/master/{{ item.conf_file }}/{{ la_cvmfs_repository }}.{{ item.ext }}'
    dest: '/etc/cvmfs/{{ item.dest_dir }}/{{ la_cvmfs_repository }}.{{ item.ext }}'
  with_items:
    - { conf_file: cvmfs_server_config_files, dest_dir: config.d, ext: conf }
    - { conf_file: cvmfs_server_keys, dest_dir: keys, ext: pub }
  notify: probe_elixir_cvmfs 
  when: elixir_it_repo
